name: Build and Push Container Image to GHCR

on:
  push:
    branches:
      - "main"
  schedule:
    - cron: "31 5 * * 1"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        name: Check out code

      - name: Set flags
        id: set_flags
        run: |
          branch="${GITHUB_REF##*/}"

          if [ "$branch" = "main" ]; then
            echo "addLatest=true" >> $GITHUB_OUTPUT
          else
            echo "addLatest=false" >> $GITHUB_OUTPUT
          fi

          if [ "$GITHUB_EVENT_NAME" = "schedule" ]; then
            echo "addTimestamp=true" >> $GITHUB_OUTPUT
          else
            echo "addTimestamp=false" >> $GITHUB_OUTPUT
          fi

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@19d2beefef6bcdc202195fdcb9deb79a4fab5c1f # v6
        with:
          image: hpilo-exporter
          registry: ghcr.io
          addLatest: ${{ steps.set_flags.outputs.addLatest }}
          addTimestamp:  ${{ steps.set_flags.outputs.addTimestamp }}
          enableBuildKit: true
          multiPlatform: true
          platform: linux/amd64,linux/arm64,linux/arm/v7
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

